name: Docker Image CI

on:
  push:
    branches: [ "main", "docker-image-ci"]
  pull_request:
    branches: [ "main", "docker-image-ci" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            tzdvorak/machinemanager:latest
            tzdvorak/machinemanager:${{ github.sha }}

